### ISSUE TITLE
[Spike] Integração com Google Maps

### ISSUE THREAD

**Issue by luismizutani** [VamosJuntas/vamosjuntas#1]
Prova de conceito para ter o mapa rodando na nossa aplicação.
Idealmente entender como:

1) Funcionamento do mapa
2) Avaliar LeafLeft que é uma biblioteca Javascript que roda sobre o Google Maps
3) Info sobre como se dá um request ao Google Maps. Ex: podemos ter isto cacheado de algum forma?

Abs

**Comment by MayraPaola** [comment]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA 
PARA 

**Dependências**

**Critérios de aceitação**
1.
DADO 
QUANDO 
DEVO 
2.
DADO 
QUANDO 
DEVO 

**Note (fazer uma próxima história):**

**Questões**
