### ISSUE TITLE
Integração de reporte de risco

### ISSUE THREAD

**Issue by Rliedke** [VamosJuntas/vamosjuntas#108]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de cadastrar um reporte de risco
PARA visualizar o report que eu cadastrei.

**Escopo:**
1. Integrar a história de front e back
2. Visualizar o risco salvo no  banco

Fora do Escopo
1. Na requisição que é feita para o banco, adicionar o nome do local para que também seja salvo ( Essa opção foi feita na história #114) 

**Historias relacionadas:**
Front end: #3 , #31
Back end: #2, #9

**Critérios de aceitação**
1.
DADO 
QUANDO eu preencho todos os dados do reporte
DEVO ver uma mensagem de sucesso de criação

História #123 que foi fechada 
Narrativa
Mudar a chamada que é feita para API, incluindo o nome do local nesta chamada.

Escopo:
Adicionar o nome do local nas informações que são enviadas ao back-end.

Critérios de aceitação:
1.
DADO que estou adicionando um novo reporte
QUANDO salvar o novo risco
DEVO salvar a informação de nome do local (exemplo: Avenida Ipiranga, 123)

DADO que estou adicionando um novo reporte
QUANDO não informo o número do endereço (exemplo: Avenida Ipiranga)
DEVO ter meu reporte salvo com uma localização aproximada baseada nos pontos do Google Maps

**Comment by gabrielacorrea** [comment]
Conforme conversado na sessão de hoje:
Na requisição que é feita para o banco, adicionar o nome do local para que também seja salvo.

**Comment by josigama** [comment]
Achei melhor separar essas funcionalidade de salvar o nome do endereço no banco. A nova história é a #114 -(Essa história foi  para fazer o back-end )

**Comment by josigama** [comment]
Essa história foi quebrada em mais um ahistória #116 para visualizar o report na lista

**Comment by josigama** [comment]
#125 closed

**Comment by josigama** [comment]
**Reportar um risco**
![image](https://cloud.githubusercontent.com/assets/13666514/22630540/43d9297a-ebe3-11e6-9bfc-01d15623939b.png)
**Reporte salvo com sucesso**
![image](https://cloud.githubusercontent.com/assets/13666514/22630545/4f984dd6-ebe3-11e6-93a2-0e31344ac2a6.png)
**Informações salvas no BD**
![image](https://cloud.githubusercontent.com/assets/13666514/22630560/78cf1022-ebe3-11e6-81db-4d90662e0e47.png)

**Salvar um report aproximado, mas sem numeração**
![image](https://cloud.githubusercontent.com/assets/13666514/22630585/18ff2b54-ebe4-11e6-9508-e631c42df504.png)
**Local foi salvo aproximado ao endereço que foi salvo com numeração**
![image](https://cloud.githubusercontent.com/assets/13666514/22630592/46aee602-ebe4-11e6-80a7-601bda75dbdf.png)
