### ISSUE TITLE
Criar serviço no Docker

### ISSUE THREAD

**Issue by Rliedke** [VamosJuntas/vamosjuntas#109]
Adicionar serviço para subir a aplicação local na maquina dos participantes.

Criar serviço e adicionar ao README

**Comment by gabrielacorrea** [comment]
Dev: @wcalderipe

**Comment by mauricioborges** [comment]
@wcalderipe @gabrielacorrea posso ajudar? Queria entender que prioridade eu sigo

**Comment by wcalderipe** [comment]
@mauricioborges toda a ajuda é bem vinda!

tu podes ver as estórias aqui waffle.io/VamosJuntas/vamosjuntas porem acho que o backlog não está priorizado.

podemos trocar uma ideia melhor amanhã (23/09) se quiseres!

**Comment by wcalderipe** [comment]
@josigama Oi, estava olhando a estória e gostaria de saber o que falta ainda já que temos um Dockerfile e instruções no README de como rodar a aplicação com o docker?

https://github.com/VamosJuntas/vamosjuntas/blob/master/Dockerfile
https://github.com/VamosJuntas/vamosjuntas#setup-with-docker-

**Comment by josigama** [comment]
@wcalderipe: O que tudo indica é que o desenvolvimento está pronto. 

Como a história está em validação seria interessante que alguém que não tenha docker instalado faça o teste do passo-a-passo e verifique se não falta nenhuma informação para subir a aplicação local com docker.

**Comment by josigama** [comment]
Back- end - validado com docker
![image](https://cloud.githubusercontent.com/assets/13666514/22171028/483fc7f8-df6d-11e6-8f52-91422bbe1a72.png)

**Comment by josigama** [comment]
Front-End - validado com Docker 
![image](https://cloud.githubusercontent.com/assets/13666514/22171231/aac21af4-df70-11e6-96a0-c40f4f6fd9ff.png)

![image](https://cloud.githubusercontent.com/assets/13666514/22171587/68cebd16-df78-11e6-8c4b-2691ef6b4bdf.png)

![image](https://cloud.githubusercontent.com/assets/13666514/22171596/84e170fc-df78-11e6-9acd-c1ffa939dc8c.png)

![image](https://cloud.githubusercontent.com/assets/13666514/22171602/97e176e8-df78-11e6-8302-6f2921b40b7b.png)
