### ISSUE TITLE
Gerar a key do Google Maps

### ISSUE THREAD

**Issue by gabrielacorrea** [VamosJuntas/vamosjuntas#110]
Precisamos conversar com a Babi para comprar uma key do Google Maps, pois a key que usamos hoje (da Raquel) pode não ser estável em produção.

Estimativa de Custos para o Google Play:  
Conta de desenvolvedor na loja do google play e pode subir mais de um app 
CUSTOS: 
- APK é 25 dólares uma única vez a taxa para publicar no google play

**Comment by wcalderipe** [comment]
Update: No showcase (16/09) conversamos com a Babi a respeito e agora estamos esperando a compra da chave.

Acho que vale a pena lembrar ela do assunto. O que tu acha @gabrielacorrea ?

**Comment by gabrielacorrea** [comment]
A Babi gerou a chave e ela foi enviada por email para todos.

**Comment by josigama** [comment]
Conforme comentário acima este card já foi validado e será fechado.
