### ISSUE TITLE
Autocomplete não está preenchendo o novo reporte

### ISSUE THREAD

**Issue by gabrielacorrea** [VamosJuntas/vamosjuntas#111]
Autocomplete não está carregando a informação de endereço da página de pesquisa para a página de novo reporte.
Na tela de busca, clica em um endereço da lista, ao ir para a página de novo reporte, ele não preenche o campo com o endereço selecionado.

**Comment by wcalderipe** [comment]
Temos mais informações a respeito? Uma imagem ajudaria. :)

**Comment by littlejuh** [comment]
@rfeijolo tinha feito uma estória relacionada que era pegar o valor do input da busca e passar pra página do reporte. Porém, isso parou de funcionar quando o autocomplete foi implementado.

**Comment by josigama** [comment]
Iniciar a busca de um endereço: 
![image](https://cloud.githubusercontent.com/assets/13666514/18805491/02c03170-81e6-11e6-82c9-7c7c1cb4e4f8.png)
Selecionar o endereço escolhido e clicar em reportar risco:
![image](https://cloud.githubusercontent.com/assets/13666514/18805503/3bcdd864-81e6-11e6-819b-28d921ea8131.png)
Visualizar que o campo endereço só vem preenchido com o que foi digitado na tela anterior:
![image](https://cloud.githubusercontent.com/assets/13666514/18805510/6e09de0e-81e6-11e6-9f50-19e173935ab2.png)

**Comment by gabrielacorrea** [comment]
Este card já foi resolvido, porém precisamos resolver o build quebrado para realizar a integração.

**Comment by josigama** [comment]
Problema do build  já resolvido  e card foi mergeado
