### ISSUE TITLE
Salvar o nome do local no BD- Back-End

### ISSUE THREAD

**Issue by gabrielacorrea** [VamosJuntas/vamosjuntas#115]
Narrativa

Escopo: 
1. Adicionar o nome do local nas informações que são enviadas ao back-end.

Critérios de aceitação
1.
DADO que estou adicionando um novo reporte
QUANDO salvar o novo risco
DEVO salvar a informação de nome do local (exemplo: Avenida Ipiranga, 123)

2.
DADO que estou adicionando um novo reporte
QUANDO não informo o número do endereço (exemplo: Avenida Ipiranga)
DEVO ter meu reporte salvo com uma localização aproximada baseada nos pontos do Google Maps

**Comment by josigama** [comment]
Adicionando um novo reporte
![image](https://cloud.githubusercontent.com/assets/13666514/22170768/6a22b866-df69-11e6-830a-63b81ff49f00.png)

Endereço salvo com o nome do local: 
![image](https://cloud.githubusercontent.com/assets/13666514/22170784/9870b394-df69-11e6-8bbc-ea3c6561af2e.png)

Endereço salvo sem a numeração: 
![image](https://cloud.githubusercontent.com/assets/13666514/22170837/385f6332-df6a-11e6-8686-d79d9e2c0676.png)

A história não foi validada pelo segundo AC, pois ele sempre utiliza a geolocalização para salvar as informações
