### ISSUE TITLE
(Front End) Visualizar a lista de locais denunciados  na home no raio de 1 km

### ISSUE THREAD

**Issue by josigama** [VamosJuntas/vamosjuntas#116]
**Valor**
 COMO uma usuária do Vamos Juntas app
 GOSTARIA de cadastrar um reporte de risco 
PARA visualizar o report que eu cadastrei. 

**Escopo** 
1. Visualizar a denuncia reportada  na lista de denuncias quando a geolocalização for até 1 KM da denúncia cadastrada.A lista de denuncias pode ser visualizada na home, conforme imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/13666514/22183932/227a50b2-e0b0-11e6-80de-26f6984dd1d5.png)

**Fora do Escopo**
1. Integrar a história de front e back 
2. Salvar o  reporte no banco 
3. Na requisição que é feita para o banco, adicionar o nome do local para que também seja salvo

**História dependente** 
#108

**Historias relacionadas** 
Front end: #3 , #31 e #108
 Back end: #2, #9, 

**Critérios de aceitação** 
**1.    Cadastrar o risco até 1KM de minha localização:** 
     DADO que eu preenchi com sucesso o formulário de risco 
     QUANDO visualizar a mensagem de sucesso na tela e voltar para a home
     ENTÃO eu deveria  visualizar  meu reporte agregado na lista de denuncias 

**1.    Cadastrar o risco a mais de  1KM de minha localização:** 
     DADO que eu preenchi com sucesso o formulário de risco 
     QUANDO visualizar a mensagem de sucesso na tela e voltar para a home
     ENTÃO eu  NÃO deveria visualizar  meu reporte agregado na lista de denuncias

**Comment by josigama** [comment]
Narrativa COMO uma usuária do Vamos Juntas app
 GOSTARIA de cadastrar um reporte de risco 
PARA visualizar o report que eu cadastrei.

Escopo: 
1. Integrar a estoria de front e back 
2. Salvar reportes no banco 
3. Visualizar a denuncia reportada 
4. Na requisição que é feita para o banco, adicionar o nome do local para que também seja salvo
Fora do Escopo


Historias relacionadas: Front end: #3 , #31 Back end: #2, #9

Critérios de aceitação 
1. 
     DADO que eu preenchi com sucesso o formulario de risco 
     QUANDO visualizar a mensagem de sucesso na tela 
      ENTÃO eu deveria  visualizar  meu reporte agregado na lista de denuncias.

**Comment by pedrro** [comment]
No critério de aceitação 1, diz que devo mostrar o reporte agregado, mas pelo que eu entendi pela conversa de ontem, não vamos mais agregar, certo?

@josigama

**Comment by pedrro** [comment]
@josigama @viniciusgama @ebragaparah, esse é o comportamento esperado na lista, mostrar os dois locais com o mesmo nome, mas com diferentes denúncias? 

<img width="260" alt="screen shot 2017-01-27 at 8 10 27 am" src="https://cloud.githubusercontent.com/assets/4137355/22367366/4d02f7ec-e468-11e6-8b34-8f06b0b930b4.png">

Eu acho que ao contrário, deveria juntar quando o local for o mesmo e  somar as denúncias para exibir na Home, o que vocês acham?

**Comment by josigama** [comment]
@pedrro : Pensamos que seria mais fácil não agregar nada, pois agrupar iria requerer um trabalho maior. A princípio simplesmente exibiríamos a informação como é retornada do back-end, mas se você acha que seria simples agrupar, não vejo nenhum problema, já que essa é uma abordagem que queremos implementar em um futuro próximo. 

Por favor de uma olhada na história #129, onde temos um desenho do possível processo de agrupamento.

Faz sentido @pedrro ?

**Comment by pedrro** [comment]
Agrupada vai seguir esse modelo que dito na #129, acho que podemos deixar agrupado já, posso prosseguir assim?

**Comment by josigama** [comment]
Sim @pedrro, pode prosseguir da forma como achar melhor! ;)

**Comment by josigama** [comment]
@pedrro  tem algum novo update dessa história? Vou pegar ela para finalizar caso você não possa continuar.
