### ISSUE TITLE
Cadastrar incidente

### ISSUE THREAD

**Issue by flmmartins** [VamosJuntas/vamosjuntas#12]

**Comment by MayraPaola** [comment]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA 
PARA 

**Dependências**

**Critérios de aceitação**
1.
DADO 
QUANDO 
DEVO 
2.
DADO 
QUANDO 
DEVO 

**Note (fazer uma próxima história):**

**Questões**
