### ISSUE TITLE
Substituir a key do Google Maps no código

### ISSUE THREAD

**Issue by josigama** [VamosJuntas/vamosjuntas#132]
**Contexto**
O cliente já enviou a Key do Google Maps por email. 
Escopo
Incluir a Key no Código 
Validar se está funcionando

**Critérios de Aceite**
Incluir uma forma de não deixar a key pública no github, pois posteriormente vai ser usada em produção.

**Notas**
Quem for implementar essa história conversar com @josigama ou @gabrielacorrea

**Comment by pedrro** [comment]
Estava pensando sobre essa estória, no escopo dela também deveria incluir uma forma de não deixar a key pública no github, pq ela posteriormente vai ser usada em produção, o que acham?

**Comment by josigama** [comment]
Perfeito @pedrro! 
Já coloquei como um critério para essa história.

**Comment by josigama** [comment]
@pedrro  estava pesquisando e a Key  dá pra  associar a um domínio e  se alguém tentar usar essa chave em outro domínio que não seja o seu,  eles receberão um alerta de JavaScript. 

http://stackoverflow.com/questions/1364858/what-steps-should-i-take-to-protect-my-google-maps-api-key

https://support.google.com/cloud/answer/6310037?hl=en

Vou pesquisar um pouco mais sobre isso e ver como podemos fazer.

**Comment by josigama** [comment]
@pedrro : A alternative que pensamos está no Pull Request, por favor validar :)
