### ISSUE TITLE
[Tech] Adicionar servidor de CI

### ISSUE THREAD

**Issue by flmmartins** [VamosJuntas/vamosjuntas#14]

**Comment by flmmartins** [comment]
Bloqueada: O Snap CI não reconheceu nosso repositório. Ticket foi aberto no SNAP http://support.thoughtworks.com/requests/26251 e caso não seja resolvido até a próxima seção vamos seguir com o Travis CI

**Comment by pedromanoel** [comment]
Observação: Não é necessário instalar todas as dependências para executar os testes.
- [ ] Descobrir como instalar somente as dependências para teste no SNAP.

**Comment by gomex** [comment]
Ao que parece os testes atuais são atendidos com o que está instalado hoje no setup.
