### ISSUE TITLE
Analisar Open Street Map

### ISSUE THREAD

**Issue by gomex** [VamosJuntas/vamosjuntas#16]

**Comment by gomex** [comment]
A ideia é analisar o uso do Open Street Map em relação ao Google Maps
- [ ] Facilidade de desenvolvimento de acesso a API
- [ ] Existência de bibliotecas da API
- [ ] Verificar se mapa está completo o suficiente para ser usado
- [ ] Analisar a adoção de outros player
- [ ] Comparar limitação de acesso a API
- [ ] Analisar questões de copyright

Vantagens iniciais
- Possibilidade de compartilhamento de dados
- Opensource
- Já existem diversas iniciativas de projetos sociais usando

**Comment by luismizutani** [comment]
Você acha que o Open Street Map é tão atualizado quanto o Google Maps? Me refiro a qualidade das informações (ex: numero de endereços, precisão das localidades, frequência de melhorias e correções).

**Comment by MayraPaola** [comment]
Sessão 2/12/15 - O grupo decidiu manter com Google Maps.
Participantes: Roberto, Felipe, Josi, Mizu, Tayane, Pamela, Pedro, Raquel, Mayra e Keithy.

**Comment by gomex** [comment]
Faz sentido manter o Google Maps mesmo :)
