### ISSUE TITLE
Buscar por endereço

### ISSUE THREAD

**Issue by flmmartins** [VamosJuntas/vamosjuntas#2]

**Comment by MayraPaola** [comment]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de buscar um endereço no mapa
PARA visualizar os reportes no local

**Escopo:**
1. Incluir um campo livre para informar o endereço de busca
2. Posicionar o ponto no endereço informado

**Dependências**
Cards: #3, #7

**Critérios de aceitação**
1.
DADO que estou visualizando o mapa
QUANDO digito o endereço X
DEVO visualizar o endereço X no mapa
2.
DADO que tenho um endereço sem numero
QUANDO digito o endereço sem o numero
DEVO visualizar um ponto central do endereço

**Note (fazer uma próxima história):**

**Questões**
1. Terá auto preenchimento no campo de busca quando estivar preenchendo?
2. Fica gravado os últimos X endereços buscados anteriormente?
