### ISSUE TITLE
Elaborar tela splash

### ISSUE THREAD

**Issue by MayraPaola** [VamosJuntas/vamosjuntas#27]
**Narrativa**
COMO uma usuária do Vamos Juntas app
QUERO 
PARA 

**Escopo:**
1.  Tela splash como exibido abaixo
<img width="324" alt="screen shot 2016-01-27 at 4 06 45 pm" src="https://cloud.githubusercontent.com/assets/13318439/12623902/6099fbf4-c513-11e5-9bd4-3ae0ca3f5399.png">

![vamos](https://cloud.githubusercontent.com/assets/13318439/12623907/67f3d230-c513-11e5-8ebd-6e18c43738fe.png)
1.  Elaborar botão ENTRAR
2. Botão ENTRAR deve permancer desabilitado até confirmação dos termos.
3. Ter testes funcionais e unitários

**Fora do Escopo:**
1. Ter página de termo de uso

**Dependências**
Sem dependência

**Critérios de aceitação**
1.
DADO  que eu acesso o app
QUANDO abre a tela
DEVO  ver a tela de splash
2.
DADO que estou no app
QUANDO eu aceito o termo de uso
DEVO entrar na tela home do app
3.
DADO que estou no app
QUANDO não aceitar o termo de uso
ENTÃO então o botão deve permancer desabilitado

**Questões**
1. Não utilizar check box, colocar um texto que ao entrar a usuária concorda com os termos de utilização.
2. Futuro: Pensar termo de utilização se terá um link para o site Vamos Juntas ou será no app?

**Link para navegação no protótipo:**
Link: https://creator.ionic.io/share/39ec7d0a7525

**Comment by tayanefernandes** [comment]
O botão deve ficar desabilitado se a usuária não marcar o "Estou de acordo com os termos"?

**Comment by pedrro** [comment]
Acho que sim @tayanefernandes, o que você acha @MayraPaola?

**Comment by MayraPaola** [comment]
@pedrro @tayanefernandes Sim, vou fazer um critério de aceitação.

**Comment by pedrro** [comment]
PR #45

**Comment by roberto** [comment]
Realizará a pergunta toda vez que a aplicação é aberta?
Talvez seja necessário, já que anônimo e não saberíamos se é a mesma pessoa utilizando na segunda vez, mas desejaria saber se é intencional sempre perguntar.

**Comment by pedrro** [comment]
Talvez tenha algum jeito de validar isso pegando alguma informação do celular.. só uma idéia pro futuro
