### ISSUE TITLE
Home - geolocalização

### ISSUE THREAD

**Issue by MayraPaola** [VamosJuntas/vamosjuntas#28]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA  de ser geolocalizada
PARA encontrar locais de risco próximos a mim

**Escopo:**
1. Geolocaliza
2. Identifica se geolocalização do aparelho está ativada
3. traz como resultado o endereço geolocalizado.
<img width="322" alt="screen shot 2016-01-27 at 4 15 08 pm" src="https://cloud.githubusercontent.com/assets/13318439/12623666/5758ca3a-c512-11e5-9a3d-5f245de7fcfc.png">
4. Ordenar a lista por por número decrescente de denúncias. 

**Dependências**
#32 (Fazer a busca de um endereço)

**Critérios de aceitação**
1.
DADO  que estou na home do app
QUANDO  estou com a geolocalização do meu aparelho ativada
DEVO ver como resultado o endereço onde estou

2.
DADO  que estou na home do app 
QUANDO  estou com a geolocalização do meu aparelho desativada
ENTÃO devo visualizar uma mensagem "informando que devo ativar a geolocalização" E devo ter a opção de ativar a partir desta mensagem

**Comment by MayraPaola** [comment]
<img width="322" alt="screen shot 2016-01-27 at 4 15 08 pm" src="https://cloud.githubusercontent.com/assets/13318439/12623647/4311e96c-c512-11e5-88ab-d9973dfd4fac.png">

**Comment by MayraPaola** [comment]
<img width="322" alt="screen shot 2016-01-27 at 4 15 08 pm" src="https://cloud.githubusercontent.com/assets/13318439/12623656/4d0f7d3a-c512-11e5-9188-a612cbb3bba6.png">

**Comment by gabrielacorrea** [comment]
A AC da estória referente a listar os riscos no raio de 1km foi movida para outra estória (#92)

**Comment by tayanefernandes** [comment]
Dev:  @tayanefernandes

**Comment by tayanefernandes** [comment]
Pull Request: https://github.com/VamosJuntas/vamosjuntas/pull/81 waiting for code review

**Comment by gabrielacorrea** [comment]
@roberto @pedroaugustofr

**Comment by MayraPaola** [comment]
@roberto @tayanefernandes @pedroaugustofr  Alguém fez desk check desta história?

**Comment by gabrielacorrea** [comment]
QA: @littlejuh
