### ISSUE TITLE
Elaborar tela home

### ISSUE THREAD

**Issue by MayraPaola** [VamosJuntas/vamosjuntas#29]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de ver a lista de locais próximos
PARA saber os lugares que eu devo evitar

**Escopo:**
1. Criar a tela home (entrada) conforme abaixo: 
![Imgur](http://i.imgur.com/BDYrto5.png)
2. Campo de BUSCA com botão
3. Lista de endereço de risco próximos a mim
4. Criar botão de reportar risco
![Imgur](http://i.imgur.com/yB18o7n.png)
5. Ter Testes Funcionais e Unitários

**Fora do Escopo:**
1. Tela do reporte
2. Detalhes da lista de endereço de risco

**Dependências**
#27 - Elaborar tela splash

**Critérios de aceitação**
1.
DADO  que aceito o termo de uso
QUANDO entro no app
DEVO entrar na tela home
2.
DADO 
QUANDO 
DEVO 

**Note (fazer uma próxima história):**

**Questões**
Essa história só será desenvolvida front-end ?

**Link para navegação no protótipo:**
Link: https://creator.ionic.io/share/39ec7d0a7525

**Comment by MayraPaola** [comment]
Quem está trabalhando neste cartão?

**Comment by tayanefernandes** [comment]
Mayra... A gente começou a trabalhar nele na quarta (eu, Felipe, Josi e Jonathan)

**Comment by josigama** [comment]
Apenas front-end! ok.
