### ISSUE TITLE
Reportar risco

### ISSUE THREAD

**Issue by flmmartins** [VamosJuntas/vamosjuntas#3]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de reportar um risco em um endereço
PARA que outras usuárias indo para aquele endereço saibam do risco

**Escopo:**
1. Ter os campos: Endereço, data, turno, classificação do risco (imagem abaixo)
2. Ter 4 opções de período (manhã, tarde, noite e madrugada) - Que horas é tarde ou noite? Isto é igual para todos? Ou todos lugares (norte sul brasil)?
3. Salvar ponto BD

Link: https://creator.ionic.io/share/39ec7d0a7525

**Dependências**
- BD deve estar funcionando

**Critérios de aceitação**
1.
DADO que eu estou no app
QUANDO  aciono o "reporte de risco"
DEVO  visualizar um formulário onde vou reportar o ocorrido.
1. DADO  que tenho outros campos de preenchimento
   QUANDO   inserir o turno do risco
   DEVO  ter as opções: manhã, tarde, noite e madrugada
2. DADO  que tenho outros campos de preenchimento
   QUANDO inserir a data do risco
   DEVO  ter a mascara de data (dd/mm/aaaa)
3. DADO  que tenho outros campos de preenchimento
   QUANDO classificar o risco
   DEVO  ter as opções de classificação para característica de local: deserto, mal iluminado, cantada agressiva, risco em potencial, cantada e roubo.

5.
DADO que preenchi todos os campos de reporte de risco
QUANDO  enviar
DEVO  ter confirmação do envio

6.
DADO que não preenchi todos os campos de reporte de risco
QUANDO  tento enviar
DEVO  receber um aviso que preciso preencher todos os campos

DUVIDA: Faz sentido ter todos os campos obrigatórios? São informações que todos os usuários terão? Ou irão querer preencher?

**Note (fazer uma próxima história):**
Poder associar futuramente em uma classificação ocorrência: roubo, assalto a mão armada..... (decidir a listagem com a Babi)
- ESTA HISTÓRIA NÃO VALIDA QUE O ENDEREÇO INSERIDO CORRETO!

**Comment by MayraPaola** [comment]
Narrativa
COMO uma usuária do Vamos Juntas app
GOSTARIA 
PARA 

Dependências


Critérios de aceitação
Poder buscar no mapa (cordenada)
Poder associar futuramente

Questões

**Comment by MayraPaola** [comment]
<img width="335" alt="screen shot 2016-03-09 at 9 27 50 am" src="https://cloud.githubusercontent.com/assets/13318439/13635284/7e88bf1a-e5d9-11e5-99f5-69bd11bc9d7d.png">

**Comment by luismizutani** [comment]
A estória me parece OK, listei abaixo algumas pequenas observações.

AC’s 1 e 2

Evitar termos vagos como QUANDO QUERO. O ideal é ter uma ação. Ex: quando clico no botão reportar risco, ou quando aciono o formulário de reportar risco

AC 3

DADO que acionei o reporte de risco
QUANDO o formulário é carregado
DEVO ver o endereço atual como default
E DEVO poder editar este endereço

Aqui seria legal ter uma espécie de desenho da interface para exemplificar como a edição funciona.

AC 4
DADO que estou editando um endereço
QUANDO preencho o campo com X letras
DEVO ver opções fornecidas pelo autocomplete (estória 60)

Não entendi bem os subitems do AC 4
Quais seriam os outros campos já preenchidos?

No AC10 eu incluiria algo que mostra qual o(s) campo(s) não preenchidos

**Comment by MayraPaola** [comment]
AC’s 1 e 2
Mas quando coloco CLICAR, não é o COMO? E isso não é legal informar?

AC 3
Coloque o protótipo no comentário vou informar!

AC 4
- Ter autocomplete no endereço do formulário de reporte de risco
- Os outros campos são os que estão no protótipo: data, turno e classificação do perigo.
  
  AC10
- Seriam todos os campos. Acha interessante escrever ou informar: igual ao protótipo?

**Comment by luismizutani** [comment]
En geral temos

ESTADO INICIAL
AÇÃO
RESULTADO

Não precisa necessariamente ser clicar em um botão, mas o ideal é ser uma ação. Tipo acessar o formulario ou ativar algo,utilizando Quero, não traduz uma ação. (lembra das estórias do Infradel, onde em vários casos aparecia... Quem eu Quero algo...) é difícil testar isso. Uma ação facilita escrever testes...

**Comment by pedrro** [comment]
Essa estória já foi feita, não? Tenho uma dúvida que podemos falar hoje na reunião. :D

**Comment by MayraPaola** [comment]
Estava com a Josi e o Otávio! ;)

Mayra Souza
Business Analyst Consultant
Email msouza@thoughtworks.com
Telephone +55 51 81143352
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=roberta-albuquerque-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>

Em 26 de abril de 2016 09:38, Pedro Henrique <notifications@github.com>
escreveu:

**Comment by gabrielacorrea** [comment]
@josigama 
Pelo que vi no app, a maior parte das ACs já estão concluídas, certo? Me corrija se eu estiver errada, mas até onde vi o que ficou faltando foi apenas buscar o endereço no BD e salvar o risco no BD.

O que tu acha de diminuirmos o escopo dessa estória, de forma que a conexão com o BD fique de fora?
Daí podemos criar outra estória para buscar o endereço e salvar o risco no BD.

Quem mais tiver sugestões para adicionar :)

**Comment by pedrro** [comment]
@gabrielacorrea Isso, o que falta para esse PR ser fechado é fazer essas alterações que a @MayraPaola pediu referente ao feedback do showcase que estão no PR #75, depois disso acho que dá pra fechar e fazer a integração do front-end com o back-end. Você pode fazer essas alterações?

**Comment by gabrielacorrea** [comment]
Obrigada @pedrro .
Já que houve um progresso nessa estória, vou criar outra para trabalharmos os ajustes citados no PR, assim desbloqueamos essa estória por agora.
A nova estória é #93

**Comment by pedrro** [comment]
@gabrielacorrea Sendo assim pode dar merge no meu PR? :D

**Comment by tayanefernandes** [comment]
@pedrro Ao preencher todos os campos e clicar em enviar, todos os campos estão ficando como inválidos:
<img width="1279" alt="screen shot 2016-06-24 at 5 42 37 pm" src="https://cloud.githubusercontent.com/assets/10910322/16350117/3071ac0c-3a33-11e6-9d15-e9dd4e10c496.png">

Poderia verificar isso?

**Comment by pedrro** [comment]
Ah sim, estava ligado nisso, mas n consegui mexer nisso ainda, pode dar uma olhada?

**Comment by gabrielacorrea** [comment]
Foi criada a estória #103 para trabalhar no bug reportado pela @tayanefernandes
