### ISSUE TITLE
Busca perigos num raio X

### ISSUE THREAD

**Issue by MayraPaola** [VamosJuntas/vamosjuntas#30]
**Narrativa**
COMO uma usuária do Vamos Juntas app
QUERO entrar no  app
PARA ver endereço de risco próximo a um ponto X (endereço fixo para teste)

**Escopo:**
1. Fazer busca no Banco de Dados [MongoDB Community](https://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/) a partir de um ponto
2. Ter raio de busca de 1km
3. Utilizando a API do Vamos Juntas
4. Usar Banco de Dados (Spike - card #21)

**Dependencias**
#68 - Configurar o CI e deploy da API

**Fora do Escopo:**
- Realizar a busca de um certo endereço na base de mapas. Vamos encontrar os perigos a partir de um ponto X fixo arbitrario.
- Reportar perigo.
- Geolocalizar endereço atual
- Buscar endereço.

**Critérios de aceitação**
1.
DADO estou em um endereço X
QUANDO faço uma consulta no banco de dados
DEVO visualizar os riscos em endereços próximos ao ponto X (endereço inicial)

**Note (fazer uma próxima história):**
Quando fizer a busca e não tiver perigo em um raio X dar feedback: "Não tem reporte de risco no raio X..."

**Questões**
- Informar o endereço que foi buscado - Localidade próximo do endereço X (uma forma de confirmação para o usuário)
- Qual será a lógica de ordenação dos resultados?
  A idea debatida era de trazer primeiramente os itens mais próximos, em caso de empate, traremos o mais recente primeiro.

**Comment by viniciusgama** [comment]
Decidimos colocar um raio de 1km pois 300m nos pareceu muito pouco. Um exemplo é que o raio da PUC é aprox 500m.

**Comment by MayraPaola** [comment]
Show!!

Mayra Souza
Business Analyst Consultant
Email msouza@thoughtworks.com
Telephone +55 51 81143352
[image: ThoughtWorks]
http://www.thoughtworks.com/?utm_campaign=roberta-albuquerque-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator

2016-05-14 17:10 GMT-03:00 Vinícius Gama notifications@github.com:

**Comment by viniciusgama** [comment]
Outra informação importante é que ao guardar as informações de localização, elas devem estar no formato [longitute, latitude], caso contrario a busca não vai funcionar.

**Comment by flmmartins** [comment]
Alguém tem q pegar essa estória ou continua-la. Testes estão comentados

**Comment by josigama** [comment]
Eu já alinhei com Vinicius e ele irá terminar a história essa semana.

**Comment by MayraPaola** [comment]
@viniciusgama  esta história foi finalizada? Foi feito desk check dela?

**Comment by gabrielacorrea** [comment]
@roberto Tem alguma pendência nessa estória?

**Comment by josigama** [comment]
Endereço Cadastrado no banco
![image](https://cloud.githubusercontent.com/assets/13666514/22176369/b6df11f0-dfef-11e6-82f0-a538fc372aa8.png)

Localizar endereço até 1 KM no maps
![image](https://cloud.githubusercontent.com/assets/13666514/22176383/21e7dd1a-dff0-11e6-9c51-d4d0c6d0bd04.png)

Medindo distancia de menos de 1KM
![image](https://cloud.githubusercontent.com/assets/13666514/22176404/ab812374-dff0-11e6-828e-c905b9735314.png)

Aparece o endereço cadastrado até 1 KM
![image](https://cloud.githubusercontent.com/assets/13666514/22176873/52678c6a-dffa-11e6-9e85-0ec86845ac3b.png)

Fazendo uma busca com mais de 1Km
![image](https://cloud.githubusercontent.com/assets/13666514/22176881/9b075f68-dffa-11e6-95c5-4613da4161df.png)

![image](https://cloud.githubusercontent.com/assets/13666514/22176890/c22f4696-dffa-11e6-88ec-816d35d882d2.png)

A busca não retorna nenhum valor: 
![image](https://cloud.githubusercontent.com/assets/13666514/22176907/ff28b758-dffa-11e6-86a1-639b07b099b5.png)
