### ISSUE TITLE
Reportar endereço de risco

### ISSUE THREAD

**Issue by MayraPaola** [VamosJuntas/vamosjuntas#31]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de reportar um endereço de risco
PARA que outras usuárias saibam do perigo

**Escopo:**
1. Criar tela de reporte de risco de acordo com layout abaixo:
<img width="318" alt="screen shot 2016-01-27 at 4 25 42 pm" src="https://cloud.githubusercontent.com/assets/13318439/12623759/c5270608-c512-11e5-8a63-749f900db503.png">
1. Criar botão enviar reporte de risco
   <img width="316" alt="screen shot 2016-01-27 at 4 26 32 pm" src="https://cloud.githubusercontent.com/assets/13318439/12623763/cc0c6800-c512-11e5-8a51-7aae071e5ea7.png">
2. Ter testes funcionais e unitários
3. Mensagem de erro para campos obrigatórios

**Dependências**
Confirmação de reporte de risco card #34

**Critérios de aceitação**
1.
DADO que estou na home do app
QUANDO quero reportar um risco
DEVO visualizar os campos de preenchimento ( conforme layout acima)
2.
DADO que vou reportar um risco
QUANDO preencho os campos
DEVO saber quais são obrigatórios (endereço, turno, data e classificação do risco)

2.
DADO que vou reportar um risco
QUANDO esqueço de preencher um campo
DEVO devo ver uma msg de erro e um feedback visual de que tem erro

---

**Fora do Escopo:**
1. Confirmação reporte
2. Salvar reporte no Banco de Dados ( salvar no banco ficará para uma próxima história)

**Note (fazer uma próxima história):**
1. Incluir do BD ou Back end o tipo do risco: ocorrência ou característica do local
2. Salvar reporte no Banco de Dados
3. Auto preenchimento do endereço:
DADO que vou reportar um risco
QUANDO preencho o endereço
DEVO ter auto preenchimento neste campo ( usar o serviço do google)

**Questões**

**Link para navegação no protótipo:**
Link: https://creator.ionic.io/share/39ec7d0a7525

**Comment by pedrro** [comment]
PR #46

**Comment by roberto** [comment]
Poderíamos deixar valores iniciais para o dia e o período, agilizando o uso da app. Que tal?
