### ISSUE TITLE
Fazer a busca de um endereço/ local

### ISSUE THREAD

**Issue by MayraPaola** [VamosJuntas/vamosjuntas#32]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA buscar um endereço
PARA que eu possa ver riscos ou reportar algo

**Escopo:**
1. Buscar um endereço (campo para entrada de dados)
2. Mostrar resultado da busca com lista de endereços ou endereço buscado
3. A ideia é exibir a lista de resultados em uma página HTML (tosco)

**Requisitos técnicos**
Integração com base de endereços do Google (serviço?)

**Critérios de aceitação**
1.
DADO que na pagina de busca
QUANDO digito endereço Rua Dom Pedro e faço a busca
ENTÃO devo ver uma lista com todas as Ruas Dom Pedro que o Google retorna (tem que trazer mais de uma)

2.
DADO que estou na pagina de busca
QUANDO digito o endereço "rua dom pedro II, 110 porto alegre"
ENTÃO devo ter um resultado e suas coordenadas (devem ser em Porto Alegre)

3.
DADO que estou  na pagina de busca
QUANDO digito um endereço que não existe (ex: lakjsdfasjkdfb)
ENTÃO devo receber um retorno de erro (provável mensagem)

4.
DADO que tenho uma lista de opções na lista (tosco)
QUANDO clico sobre a opção que desejo
ENTÃO o ponto selecionado devera alimentar a busca por riscos reportados naquele raio (ver história #30 - Busca de perigo num raio  X)

**Comment by tayanefernandes** [comment]
Validação ok.
Precisa fazer demo com a PO
