### ISSUE TITLE
Visualizar lista do reporte de risco por classificação

### ISSUE THREAD

**Issue by MayraPaola** [VamosJuntas/vamosjuntas#35]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de ver os detalhes do reporte de risco
PARA  saber se o local esta seguro

**Comportamento**
Da lista de locais (home geolocalizada #28) eu acesso o detalhes do reporte de risco.

**Escopo:**
2. Criar tela de detalhe do reporte
3. Tela conforme o layout abaixo: 
<img width="379" alt="screen shot 2016-01-29 at 6 20 33 pm" src="https://cloud.githubusercontent.com/assets/13666514/12687164/47fa2cd8-c6b5-11e5-9587-b715d2ed98b6.png">

**Critérios de aceitação**
1.
DADO estou no detalhe do reporte 
ENTÃO posso visualizar nome e as características do local

2.
DADO estou no detalhe do reportes
ENTÃO posso fazer um reporte

**Comment by josigama** [comment]
Essa história precisa ser  terminada, mas já está comitada na branch.

**Comment by pedrro** [comment]
PR #48

**Comment by marcelopv** [comment]
Validated and looks good to me 👍

**Comment by marcelopv** [comment]
QA: @marcelopv
