### ISSUE TITLE
Autocomplete no campo de reportar

### ISSUE THREAD

**Issue by josigama** [VamosJuntas/vamosjuntas#39]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de ajuda para inserir um endereço
PARA facilitar em minha busca/reporte de risco. 

**Escopo:**
1. Usar o search box do google maps API no campo de endereço (tela reporte de risco - #31) e no campo de busca de endereço (tela home- #29). 
2. Não haver duplicidade de um endereço reportado. 
3. Aplicar autocomplete no campo da home e na página de reportar risco

Dependência:
- Estória de reportar perigo

**Critérios de aceitação**
1.
DADO que busco por um endereço
ENTÃO devo ver as sugestões de API

2.
DADO que busco por um endereço 
E não existe sugestão
ENTÃO não devo exibir sugestão de adicionar endereço
E devo permitir o usuário buscar pela palavra digitada

3.
DADO que não escolho uma das sugestões 
ENTÃO devo permitir o usuário buscar pela palavra digitada

**Comment by tayanefernandes** [comment]
Essa funcionalidade já está sendo desenvolvida na história: #60
