### ISSUE TITLE
Atualizar categorias de risco

### ISSUE THREAD

**Issue by flmmartins** [VamosJuntas/vamosjuntas#5]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de visualizar as categorias de risco
PARA que eu possa classificar o risco

**Critérios de aceitação**
1.
DADO que estou na tela de reportar denúncia
QUANDO eu selecionar a opção Risco
DEVO visualizar as seguintes opções: 
- Assédio sexual
- Assédio verbal
- Estupro
- Latrocínio
- Local deserto
- Mal iluminado
- Potencial à risco
- Praça deserta
- Propriedade abandonada
- Roubo
- Rua sem saída
- Terreno baldio

**Comment by MayraPaola** [comment]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA 
PARA 

**Dependências**


**Critérios de aceitação**
1.
DADO 
QUANDO 
DEVO 
2.
DADO 
QUANDO 
DEVO 

**Note (fazer uma próxima história):**


**Questões**

**Comment by tayanefernandes** [comment]
Dev: @tayanefernandes

**Comment by gabrielacorrea** [comment]
QA: @gabrielacorrea
