### ISSUE TITLE
Funcionalidades da Tela Home

### ISSUE THREAD

**Issue by MayraPaola** [VamosJuntas/vamosjuntas#58]
**Funcionalidades da Tela  Home**
1. #29 - Tela home
    1.1 - Geolocalização: #28 - Geolocalização
     1.2 - Busca: #32 - Fazer busca de endereço
    1.2 - Detalhes do risco: #35 - Detalhes do reporte de risco
    1.3 - Reportar risco:  #31 - Reportar endereço de risco (cadastro)

Link: https://creator.ionic.io/share/39ec7d0a7525

**Comment by gabrielacorrea** [comment]
Issue duplicada.
