### ISSUE TITLE
Integração das telas - Fluxo detalhes do reporte de risco

### ISSUE THREAD

**Issue by MayraPaola** [VamosJuntas/vamosjuntas#59]
**Escopo**
1. Validar a integração entre as telas, conforme o fluxo descrito abaixo.

**Fluxo das Telas**
1. #27 - Tela Splash
2. #29 - Tela home: clicar no risco
3. #35 - Visualizar os detalhes do reporte de risco
4. #31 - Reportar endereço de risco (cadastro)
5. #34 - Confirmação de reporte
6. Volta para tela home: #29 - Tela home: 
Link: https://creator.ionic.io/share/39ec7d0a7525

**Comment by pedrro** [comment]
Ao clicar no local/risco o usuário não é direcionado a tela de detalhe do reporte de risco.

**Comment by tayanefernandes** [comment]
Validado local.
