### ISSUE TITLE
Autocomplete da Busca e Reporte de Risco

### ISSUE THREAD

**Issue by MayraPaola** [VamosJuntas/vamosjuntas#60]
**Narrativa**
COMO usuário do Vamos Juntas
GOSTARIA de ver recurso de autocomplete de endereço
PARA que eu possa encontrar rapidamente o endereço correto

**Dependências**
- Estória #32 (integração com Google)
-  Estória #

**Escopo:**
- Listar resultados em formato de autocomplete no campo endereço: de busca e reporte de risco
- Permitir seleção do endereço correto ao tocar na busca e reporte de risco
- Integração com endereços do Google deve estar funcionando (busca e reporte de risco)

**Critérios de aceitação**
BUSCA:
1.
DADO que estou na pagina de busca/ reporte risco
QUANDO digito endereço Rua Dom Pedro
ENTÃO devo ver uma lista com todas as Ruas Dom Pedro exibidas em formato autocomplete

2.
DADO que tenho uma lista de opções na lista autocomplete
QUANDO clico sobre a opção que desejo
ENTÃO o ponto selecionado devera alimentar a busca por riscos reportados naquele raio (ver história #30 - Busca de perigo num raio  X)

REPORTE DE RISCO:
2.
DADO  que estou editando um endereço
QUANDO  insiro um novo endereço (ou X letras)
DEVO  ter o autocomplete do endereço (estória 60)
E poder selecionar o endereço que me interessa

**Note (fazer uma próxima história):**

**Questões**

**Comment by littlejuh** [comment]
Estavamos com um erro por causa da API Key do gmaps e aparentemente esse problema foi resolvido. 
Ver com a Babi uma nova API Key. @Rliedke

**Comment by Rliedke** [comment]
Bem lembrado Ju, vou pedir a Babi.

Em 2 de ago de 2016 9:12 PM, "Juliana Fernandes" notifications@github.com
escreveu:

**Comment by MayraPaola** [comment]
Quando fizer a DEMO com a Babi temos que comunica-la que precisamos que ela faça o pagamento da API Key do Google Maps! ;)
@littlejuh e @Rliedke  tem mais detalhes sobre esse assunto.
