### ISSUE TITLE
Configuração snap - Testes Funcionais

### ISSUE THREAD

**Issue by josigama** [VamosJuntas/vamosjuntas#66]
Configurar a task dos testes funcionais no stage do Snap.

**Comment by josigama** [comment]
Aguardando uma solução do snap para o start da aplicação em background para que os testes funcionais possam rodar. Um email foi enviado para o support da Thoughtworks.

**Comment by flmmartins** [comment]
Problema do Ionic resolvido. Agora estamos com outro problema pq os testes não estão detectando o ionic.
