### ISSUE TITLE
Configurar o CI e deploy do backend

### ISSUE THREAD

**Issue by MayraPaola** [VamosJuntas/vamosjuntas#68]
**Narrativa**
Como um membro da equipe Level Up
Gostaria de ter um pipeline de deploy configurado no CI
Para que possamos por em produção cada alteração/atualização feita na Api

**Escopo:**
1. Configurar Snap CI (Backend)
2. Rodar testes Unitários
3. Rodar testes funcionais

**Fora do Escopo:**

**Dependências**

**Critérios de aceitação**
NA
**Note (fazer uma próxima história):**

*\* Notas:
Essa estória só cobre a configuração da API de forma independente.  A partir do momento que fizermos a integração de fato do front com o backend  ai vamos criar as estórias de ponta a ponta. Logo a estória deve fazer deploy tanto para front quanto para back.

**Questões**
- O deploy de API é necessário para poder conectar aos dados do app?
  => R: Sim. 
- Teremos ambiente de Staging?
  R: Não. Atualmente o Heroku que temos é só prod já que ainda não estamos disponibilizando o ap para o público
- Após testes serem concluídos as alterações serão automaticamente promovidas para produção? Ou isto será um comando manual?
  Atualmente as alterações vão para produção a cada commit. Podemos alterar isso.

Como é o fluxo? Alguém sabe explicar?
Você faz commit e ele roda. Se ele passar nos testes estará em produção automaticamente

**Comment by gabrielacorrea** [comment]
Oi @flmmartins , Como podemos validar a estória? Qual a URL do endpoint?
@marcelopv @tayanefernandes

**Comment by flmmartins** [comment]
@gabrielacorrea não há endpoint. O que fizemos nessa estória foi só o CI do backend aqui:https://snap-ci.com/VamosJuntas/back-end/branch/master

Também colocamos o backend em um servidor no Heroku aqui https://vamosjuntasdb.herokuapp.com (já que é só um banco de dados você não deve ver nenhuma página web mas pode abrir o RoboMongo e consultar o banco)

Acho que essa aqui é a URL de administração dos VamosJuntas frontend e backend.
https://dashboard.heroku.com/pipelines/d8686918-ed0d-4c9c-a145-9e4a2081c001

Se não conseguir por essa URL tens q entrar na sua conta do Heroku e ver.

Atualmente somente algumas pessoas do projeto tem acesso. Tem que adicionar uma pessoa por vez porque temos uma conta free no Heroku e tem essa limitação.

Atualmente a Babi (owner do Heroku), eu, @josigama, @otaviocarvalho, @Rliedke, @tayanefernandes tem acesso

Se alguém mais precisar acesso, me avisa ou algum das pessoas acima.

**Comment by flmmartins** [comment]
Basicamente se o CI ta funcionando. Ta todo mundo desenvolvendo feliz e acessando o Heroku essa seria a validação da estória

**Comment by tayanefernandes** [comment]
Dev: @flmmartins 
QA: @tayanefernandes

História validada. CI e banco funcionando.
Não precisa de demo com a PO.
