### ISSUE TITLE
Endereço da busca ir para o campo de endereço do reporte (default)

### ISSUE THREAD

**Issue by MayraPaola** [VamosJuntas/vamosjuntas#69]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA visualizar o endereço digitado no campo de BUSCA na tela de REPORTE no campo endereço
PARA eu não precisar digitar o endereço novamente

**Escopo:**
1. Copiar o endereço do campo de busca para o campo de endereço no reporte
2. Poder editar o endereço no reporte

**Requisitos técnicos**

**Dependência**
#3 - Reporte de risco
#32 - Busca de um endereço

**Critérios de aceitação**
1.
DADO que fiz a busca de um endereço X
QUANDO quero reportar um risco
ENTÃO devo ver o endereço X buscado no campo de endereço de reporte

2.
DADO que vou reportar um risco
QUANDO vejo o endereço que havia colocado no campo de busca
E quero alterar
ENTÃO devo poder editar o endereço

3.
DADO 
QUANDO 
ENTÃO

**Comment by rfeijolo** [comment]
PR #90

**Comment by gabrielacorrea** [comment]
Dev: @rfeijolo

**Comment by tayanefernandes** [comment]
QA: @tayanefernandes
