### ISSUE TITLE
Mostrar no mapa onde estou

### ISSUE THREAD

**Issue by luismizutani** [VamosJuntas/vamosjuntas#7]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de ver o mapa indicando a minha localização atual
PARA visualizar rapidamente a região onde estou

**Dependências**
1. Mapa tem de estar integrado card #1
2. Ionic (precisa integração?) - app instalado?

**Critérios de aceitação**
1.
DADO que estou local X (endereço:??) 
QUANDO abrir o mapa 
DEVO ser aberto indicando (pin) o local X (endereço:??)

**Task de dev**
- [ ] Parametrizar chave de API 

**Questões**
- Como funciona a geolocalização sem o funcionamento do Wi-fi?

**Comment by pedrro** [comment]
Quem está fazendo essa?
