### ISSUE TITLE
Adicionar docker

### ISSUE THREAD

**Issue by wcalderipe** [VamosJuntas/vamosjuntas#87]
- Adicionar os arquivos de configuracão
- Fazer o BD ler estes arquivos 
- Testes passarem

**Comment by gomex** [comment]
Podem contar comigo nessa :)

**Comment by wcalderipe** [comment]
@gomex as issues abertas no mingle relacionadas ao repositório back-end estão sendo enviadas par cá. A PR já foi feita se tu quiser dar uma revisada o link é esse aqui [#87](https://github.com/VamosJuntas/back-end/pull/12) =)
