### ISSUE TITLE
Listar riscos no raio de 1km

### ISSUE THREAD

**Issue by gabrielacorrea** [VamosJuntas/vamosjuntas#92]
**Valor**
COMO uma usuária do Vamos Juntas app
GOSTARIA de visualizar uma lista dos riscos dentro do raio de 1km
PARA encontrar locais de risco próximos a mim

**Escopo** 
1. Filtrar os riscos cadastradas no raio de 1km na home. Image abaixo: 
![image](https://cloud.githubusercontent.com/assets/13666514/22186842/a68ac50c-e0e3-11e6-8a1b-31fae1cd6057.png)

2. Ordenar a lista por data, sendo que as denúncias reportadas recentemente aparecerão primeiro
3. Ter um limite de exibição de até 10 denuncias cadastradas

**Dependências**
#30 (Buscar perigos num raio x)

**Critérios de aceitação**
DADO que estou na home do app
QUANDO verificar a localização da usuária
DEVO ver como resultado a lista dos riscos reportados  no raio de 1 KM

**Comment by Rliedke** [comment]
Bloqueada pelo refactoring da #3. Assim que terminada por favor remover a tag blocked.

**Comment by tayanefernandes** [comment]
Perguntas:
- Devemos sub agrupar as ocorrências que estejam próximas, quando pesquisamos os locais próximos a mim? Ou devemos listar todas as ocorrências sem agrupar e ordenando por distância? Não lembro o que foi definido sobre isso :/
  ![3](https://cloud.githubusercontent.com/assets/10910322/18294079/201b9e70-746d-11e6-9a4c-5d59283e9e6c.JPG)
  ![2](https://cloud.githubusercontent.com/assets/10910322/18294080/22b9ba04-746d-11e6-9b15-b5ce40a3c446.JPG)
-  As ocorrências devem ter o titulo salvo no banco ou devemos buscar isso no google maps quando estamos fazendo a busca?

@gabrielacorrea @roberto @taniadgv

**Comment by gabrielacorrea** [comment]
@tayanefernandes Acredito que podemos listar por distância.
O título se buscarmos do Google Maps ele vai estar padronizado, o que se buscarmos pelo formato em que ele foi salvo no banco, pode ter inconsistências. Daí eu acredito que pelo Google Maps é melhor.

@roberto @taniadgv o que vocês acham disso?

**Comment by gabrielacorrea** [comment]
Esta estória está bloqueada pelas estórias

**Comment by gabrielacorrea** [comment]
Esta estória está bloqueada por #108 de front-end e #14 de back-end.
Precisamos salvar no banco o nome do local também, além das informações já inseridas.
Dessa forma, usaremos essa informação salva para mostrar na lista de reportes do local.

**Comment by josigama** [comment]
Bloqueada pelos cards #115, #123, #108, #121

**Comment by josigama** [comment]
Respondendo o comentário acima de tayanefernandes commented on Sep 6, 2016
Para o MVP1 não vamos agrupar as ocorrências que estejam próximas, vamos exibir todas que foram cadastradas no raio de 1 KM da localização do usuário. 

Para o MVP2 vamos agrupar as ocorrências que estejam próximas. 
Isso deverá ser feito na história #129
