### ISSUE TITLE
Ajustar campos da tela Reportar Risco

### ISSUE THREAD

**Issue by gabrielacorrea** [VamosJuntas/vamosjuntas#93]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de reportar um risco
PARA que eu possa compartilhar essa informação com outras usuárias

**Escopo**
Com base no feedback da estória #3, foi solicitado:
1. Alterar o campo data para o padrão brasileiro
2 Alterar o campo turno para hora: formato hh:mm

**Critérios de aceitação**
1.
DADO que eu esteja reportando um risco
QUANDO eu preencher o campo de data
DEVO visualizar o padrão brasileiro de data

2.
DADO que eu esteja reportando um risco
QUANDO eu preencher o campo de turno
DEVO visualizar o campo com o formato hh:mm

**Comment by marcelopv** [comment]
Como o novo campo de data irá conter data e hora, não é mais necessário o uso do campo período. @gabrielacorrea seria bom confirmar se o back-end usa esse campo, em caso afirmativo, é necessário removê-lo.

Fiz uma pesquisa para identificar se existe alguma forma de configurar o formato de um campo do tipo data na tela do usuário, e encontrei que o formato visualizado no browser é definido através das preferências de região do usuário configurada pelo dispositivo (Mac, iPhone, Android). Desta forma não é necessário se preocupar com o formato.

**Comment by marcelopv** [comment]
DEV: @marcelopv

**Comment by tayanefernandes** [comment]
QA: @tayanefernandes

**Comment by tayanefernandes** [comment]
Validado no simulador do iphone e no android real em português. Formato está ok de acordo com a lingua/região configurada no dispositivo do usuário.
