### ISSUE TITLE
Salvar reporte de risco no BD

### ISSUE THREAD

**Issue by gabrielacorrea** [VamosJuntas/vamosjuntas#94]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de reportar um risco em um endereço
PARA que outras usuárias indo para aquele endereço saibam do risco

**Escopo**
1. Pesquisar endereço
2. Salvar risco no BD

**Dependências**
1. BD

**Critérios de aceitação**
1.
DADO que eu reportei um risco
QUANDO clico em enviar
DEVO salvar este risco no BD

2.
DADO que eu reportei um endereço x 
QUANDO consulto um endereço na home do app
DEVO visualizar o risco que salvei anteriormente

**Comment by marcelopv** [comment]
@gabrielacorrea Olhando a label desta story está dizendo que ela é front, porém não seria back-end uma vez que é necessário salvar no banco de dados?

**Comment by tayanefernandes** [comment]
Criei a história #15 no back-end. Vou mover essa história como duplicada.
