### ISSUE TITLE
Página termos de condições de uso

### ISSUE THREAD

**Issue by gabrielacorrea** [VamosJuntas/vamosjuntas#97]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de ler os termos de aceitação e uso
PARA que eu esteja ciente dos termos 

**Escopo**
1. Quando clicar no link da página abrir um [pop up](http://ionicframework.com/docs/api/service/$ionicPopup/)
2. Salvar no dispositivo quando a usuária aceitar os termos de uso
3. Seguir o layout abaixo: 
![vj-terms 1](https://cloud.githubusercontent.com/assets/13666514/22630725/0c6d35a0-ebe6-11e6-80c8-59ccee358fd6.png)

**Dependências**
Utilizar os termos de uso enviados pela cliente na história #101 

**Critérios de aceitação**
DADO que instalei o aplicativo
QUANDO acessar o aplicativo pela primeira vez
DEVO visualizar a opção de aceitar os termos de uso

DADO que quero ler os termos de uso
QUANDO eu clico no link
DEVO visualizar uma pagina com o conteudo desejado.

DADO que já utilizei o aplicativo
QUANDO acessá-lo novamente
DEVO visualizar a home page

**Comment by gabrielacorrea** [comment]
Enquanto não tivermos o texto dos termos prontos, vamos desenvolver esta estória e exibir um texto ilustrativo.
Quando a Babi nos retornar os Termos, faremos a atualização do texto exibido.

**Comment by josigama** [comment]
![image](https://cloud.githubusercontent.com/assets/13666514/22810044/6a40040c-ef1d-11e6-9a66-0e026b6ccb20.png)

![image](https://cloud.githubusercontent.com/assets/13666514/22810059/822efb0e-ef1d-11e6-9525-4431199e3d84.png)
