### ISSUE TITLE
Adicionar botão de voltar nas telas

### ISSUE THREAD

**Issue by gabrielacorrea** [VamosJuntas/vamosjuntas#98]
**Narrativa**
COMO uma usuária do Vamos Juntas app
GOSTARIA de voltar para a tela anterior
PARA que eu possa desfazer uma ação

**Escopo**
1. Validar que ao acessar o app pelo telefone, o botão de voltar está disponível

**Dependências**

**Critérios de aceitação**
1.
DADO que 
QUANDO 
DEVO

**Comment by pedrro** [comment]
Já foi feito no PR #75, pode ir para validação

**Comment by tayanefernandes** [comment]
QA: @tayanefernandes

**Comment by tayanefernandes** [comment]
Validado.
